---

sentry_user: sentry

sentry_network: sentry

sentry_data_volume: sentry-data

sentry_db_volume: sentry-db

sentry_image: sentry:9.1

sentry_db_user: postgres

sentry_db_name: postgres

sentry_db_password: ""

sentry_port: 9000
