---

pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCq/gAKXz6C2zzYcnjs9BUnyry8h+bSAy3/3w6e1dgZx+ZoY1ZoAi7KcREMkG4M6SJ1AbQVezCX0yntoQ9gZz8uRNwT3pFUsvfWAKIvRrdEd5nutglcB9bCn1AL+EeKirrBATZjePES+F2Do82HmIX7Y3urynU0cHi9j76ZPAoxgmeN7ZJdsVC6zek6VQDW+ExwUKMEeHU8QQge5IQjiyGGERXUjCcnfeOw0rytkN4ARrz34cmkx9gqI5DzK9ebhMmB5/UQHzg+bk+yhPemcYpbN/OyA92Oua7qasucWEo4AZ/bxOLDEIR2M5LDglFmJkCdBnWvkC5NXZ7Ol/XESbI3 bbt@sergei-arch-2016-11-21"
