---

pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC30UIAqIc5xROlf9qsAaCqUicJBTh8cewB6zQ+OObcNJLtAiJUIfxs6sTupyymVw4dPOnf2SLhw8E2vy1nAbdVBCKAwh40rfcStiRfEE0j71feRAnw+xtKfZBRU/rJ0HFYcvzVfHa1X0F8IKbWSCWjQUYcyaaCfXpt8HpGdK/Xy9Gk9T07ws1qLwpnMmCcm47IskfIacvZ+lOvIJw3DY8ESV0INO9kJRDh3VhP2cR4Ha7JnFLCUYdw2j/PNZJEXInRXBOEDKq1olBtSL1ji9528LF4DxfdciGtJEkpcIEaHj6OGsIPOAuuuCNR6F2vzmA7F4NqsmoTJ3sE3Dyn9cjR bbt@bbt-laptop"
